### ISSUE TITLE
Parts will not show up in VAB or SPH

### ISSUE THREAD

**Issue by llampshade** [shadowmage45/KerbalFoundries2#18]
Hello! I was able to download the parts and install them no problem, and they loaded in game, but when i went to add them on a draft, the were not available. did i install them wrong or something?

**Comment by shadowmage45** [comment]
Chances are that there is something incorrect with your installation that is preventing the parts from loading.  This could be missing dependencies, incorrect installation path, or even version mismatch.

Are you in career mode, and do you have the proper tech-node unlocked (it is very late on the tech-tree)?  Do the parts show up in the editor parts list at all?

Would you mind uploading your KSP.log file?  This should contain most of the information I would need to diagnose this problem.

**Comment by llampshade** [comment]
I'm using the sandbox game mode, so it isn't that. sorry to ask, but where can i find the logs?

**Comment by shadowmage45** [comment]
It should be in your main KSP folder.  The exact location would depend on what OS and installation method you used.    
More instructions can be found here:  http://forum.kerbalspaceprogram.com/index.php?/topic/83212-how-to-get-support-read-first/
and here: http://wiki.kerbalspaceprogram.com/wiki/Root_directory

(that first link is wrong;  I **do not** want the output.txt, I **do want** the KSP.log file;  the KSP output has changed since that post was made, and it was never updated to reflect the proper log file names/locations)

**Comment by llampshade** [comment]
[output_log.txt](https://github.com/shadowmage45/KerbalFoundries2/files/1191534/output_log.txt) not sure if this is the right one, but it is the only log file that would attach to this.

**Comment by shadowmage45** [comment]
Your problem is that you have things installed in the wrong directory/folder structure; you have a nested GameData folder that should not be there.  

Currently your game is setup like:
GameData/GameData/KerbalFoundries/
GameData/GameData/KSPWheel/
GameData/GameData/ModuleManager.2.8.1.dll

It needs to be setup like:
GameData/KerbalFoundries/
GameData/KSPWheel/
GameData/ModuleManager.2.8.1.dll

**Comment by llampshade** [comment]
hey, it works! thats a ton, cant wait to enjoy the mod. thanks!

**Comment by shadowmage45** [comment]
Glad that sorted it out for you :)

Please remember that folder/setup for installing other mods in the future, many of them use a similar distribution folder setup as KerbalFoundries.
