### ISSUE TITLE
compatibility with TweakScale.....

### ISSUE THREAD

**Issue by ghost** [shadowmage45/KerbalFoundries2#2]
i notice that when i up-scaled the tank tracks to 3x the original and then launched them, it seems that it is a bit....smaller.....was wondering if there's a fix to that...thank you!

**Comment by shadowmage45** [comment]
Tweakscale is not supported (and should not be needed)

Are you using the built-in scaling, or is Tweakscale also installed / messing with things?

Pics of the craft in editor with right-click menu open, and once launched with right-click menu open would be helpful.

Log files are also going to be needed so that I can see if Tweakscale is installed and messing with things that it shouldn't.

**Comment by ghost** [comment]
I did install tweakscale,  tho I used the built in resizing tool from the foundries mod.... I'll send the pics soon...

**Comment by ghost** [comment]
![screenshot6](https://cloud.githubusercontent.com/assets/24465649/22040308/7215fc68-dcd0-11e6-9066-6bddbce325a2.png)
![screenshot7](https://cloud.githubusercontent.com/assets/24465649/22040309/7218df46-dcd0-11e6-91eb-f42210316ab1.png)

**Comment by shadowmage45** [comment]
You have a bad install -- it is causing two KSPWheelBase modules to be present;  the scale on one is overwriting the scale on the other.

As per the latest release notes -- DELETE the entire KSPWheel folder, and re-install the mod from the latest KerbalFoundries release.
